services:
  - type: web
    name: faceattend-backend
    env: python
    region: oregon  # Choose closest to Kenya: frankfurt or singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: faceattend-db
          property: connectionString

databases:
  - name: faceattend-db
    databaseName: faceattend
    user: faceattend
    plan: free